---
title: "Day 4 - Exploring Data"
author: "Wade Sedgwick"
format: html
editor: visual
---

```{r}


library(tidyverse)
library(palmerpenguins)
library(GGally)
library(skimr)
```

## Exploratory Data Viz

Check out your data a bit:

```{r}


# Tell me the column names
names(penguins)

# What are the dimensions
dim(penguins)

# Can you show me the first 6 lines?
head(penguins)

# Can you show me the last 6 lines?
tail(penguins)


```

```{r}
skim(penguins)

GGally::ggpairs(penguins)

```

## Jitterplot

Flipper Length by Species

```{r}
ggplot(data = penguins, aes(x = species, y = flipper_length_mm)) +
  geom_jitter(width = 0.2,
              alpha = 0.8,
              aes(color = species)) +
  geom_boxplot(fill = NA,
               width = 0.5) +
  theme_light() +
  scale_color_manual(values = c("darkorchid4", "cyan4", "goldenrod")) +
  labs(x = "Penguin Species",
       y = "Flipper Length (in mm)",
       title = "Palmer Arc. Penguin Flippers")
```

```{r}
ggplot(data = penguins, aes(x = bill_length_mm)) +
  geom_histogram(aes(fill = species), color = "magenta") +
facet_wrap(~species, ncol = 1)
```

```{r}

species <- penguins$species

adelie <- filter(penguins, species == 'adelie')


flipper_mean <- mean(penguins$flipper_length_mm, na.rm = TRUE)
flipper_mean

ggplot(data = penguins, aes(x = island, y = flipper_length_mm)) +
 geom_jitter(aes(color = species))

ggplot(data = penguins, aes(x = body_mass_g)) +
  geom_histogram()


```

```{r}

bear <- c(5, 8, 12)

as.character(bear)

bear

as.numeric(bear)

```


```{r}

r <- c(5, 2, 1, 8, 45)

r * 2

is.na(r)

is.numeric(r)

class(r)

# Changes in R Studio




```




